whole_style_list = [
        #################   styles   ########################
    "Abstract Expressionism", "Art Nouveau", "Avant-Garde", "Bauhaus", 
    "Baroque", "Classicism", "Conceptual Art", "Constructivism Art", 
    "Abstract Art", "Analytical Cubism", "Art Deco", "Ashcan School", 
    "Afrofuturism", "ASCII art", "Barbizon school", "Classical Realism", 
    "Cloisonnism", "COBRA", "Dada", "Dansaekhwa", "Pop Art", "Surrealism", 
    "Realism", "Impressionism", "Neo-Impressionism", "Post-Impressionism", 
    "Fauvism", "Renaissance Art", "Romanticism", "Neoclassicism", 
    "Academic Art", "Ancient Art", "Hyperrealism", "Fauvism", "Expressionism", 
    "Cubism", "Futurism", "Dadaism", "Surrealism",
    "Minimalism", "Abstract Illusionism", "Rococo", "Tonalism", "Symbolism",
    "Constructive Realism", "Neoplasticism", "Suprematism", "De Stijl", "Precisionism",
    "Social Realism", "New Objectivity", "Precisionism", "Tenebrism", "Photorealism",
    "Op Art", "Kinetic Art", "Informalism", "Art Brut", "Neo-Expressionism",
    "Transavantgarde", "Spatialism", "Art Informel", "Orphism", "Rayonism",
    "Purism", "Divisionism", "Ornamental Art", "Naïve Art", "Magic Realism",
    "Ephemeral Art", "Land Art", "Body Art", "Happening", "Fluxus",
    "Installation Art", "Video Art", "Street Art", "Graffiti Art", "Digital Art",
    "Net Art", "Sound Art", "Bio Art", "Cybernetic Art", "Augmented Reality Art", 
    "Hard-Edge Painting", "Lyrical Abstraction", "Pattern and Decoration", "New Realism", 
    "Arte Povera", "Spatialism", "Nouveau Réalisme", "Figurative Expressionism", 
    "Abstract Surrealism", "Automatism", "Existential Art", "New Image Painting", 
    "Verism", "Postmodernism", "Metaphysical Painting", "Precisionism", 
    "Rappel à l'ordre", "Eastern Bloc Art", "Contemporary Realism", "Conceptual Realism", 
    "Neo-Conceptual Art", "Post-Minimalism", "Hard-Edge Painting", "Neo-Geo", 
    "Neo-Op", "Figuration Libre", "Bad Painting", "Pattern and Decoration", 
    "Radical Chic", "Neue Sachlichkeit", "Nouvelle Athènes", "Superflat", 
    "Pop Surrealism", "Lowbrow", "Kitsch Movement", "Toyism", "Magical Realism", 
    "Fantastic Realism", "Precisionism", "Nabis", "Synthetism", 
    "Cloisonnism", "Hudson River School", "Rock Art", "Cave Painting", 
    "Aboriginal Art", "Inuit Art", "Oceanic Art", "African Art", 
    "Native American Art", "Latin American Art", "Islamic Art", "East Asian Art", 
    "Indian Art", "Southeast Asian Art", "Central Asian Art", "Oceanian Art", 
    "Australian Art", "Antarctic Art", "Eclecticism", "Transcendental Painting", "Metarealism", "Stuckism", 
    "International Gothic", "Romanesque Art", "Gothic Art", "Proto-Renaissance", 
    "Northern Renaissance", "Mannerism", "High Renaissance", "Mughal Painting", 
    "Sogdian Art", "Korean Art", "Tang Dynasty Art", "Song Dynasty Art", 
    "Yuan Dynasty Art", "Ming Dynasty Art", "Qing Dynasty Art", "Edo Period Art", 
    "Meiji Period Art", "Taisho Period Art", "Showa Period Art", "Heian Period Art", 
    "Kamakura Period Art", "Muromachi Period Art", "Azuchi-Momoyama Period Art", "Edo Period Art", 
    "Nara Period Art", "Asuka Period Art", "Jomon Period Art", "Yayoi Period Art", 
    "Joan's Circle", "CoBrA Movement", "Lettrism", "Noigandres Group", 
    "Nabis", "Synthetism", "Secessionism", "Wiener Werkstätte", 
    "Ashcan School", "The Eight", "Ten American Painters", "Mexican Muralism", 
    "Grupo Montparnasse", "Die Brücke", "Der Blaue Reiter", "Bauhaus", 
    "De Stijl", "Neue Sachlichkeit", "Tachisme", "Spatialism", 
    "Supports/Surfaces", "Art Concret", "Op Art", "Zero Group", 
    "Arte Povera", "Fluxus", "Happenings", "Body Art", 
    "Land Art", "Earthworks", "Site-Specific Art", "Institutional Critique", 
    "Appropriation Art", "Neo-Geo", "Pattern and Decoration", "Stuckism", 
    "Abstract Illusionism", "Digital Art", "Net Art", "Cybernetic Art", 
    "Post-Internet Art", "Bio Art", "Data Art", "Generative Art", 
    "Interactive Art", "Mixed Media Art", "Multimedia Art", "Virtual Reality Art", 
    "Street Art", "Graffiti Art", "Muralism", "Stencil Art", 
    "Sticker Art", "Yarn Bombing", "Video Game Art", "Game Art", 
    "Conceptual Art", "Process Art", "Systems Art", "Performance Art", 
    "Body Art", "Fluxus", "Happenings", "Installation Art",
    "Avant-Garde", "Punk Art", "Gothic Art", "Romanticism", 
    "Symbolism", "Aestheticism", "Decadent Movement", "Pre-Raphaelite Brotherhood", 
    "Arts and Crafts Movement", "Art Nouveau", "Wiener Werkstätte", "Secessionism", 
    "Precisionism", "Precisionist Architecture", "Abstract Illusionism", "Social Realism", 
    "American Scene Painting", "Magic Realism", "Fantastic Realism", "New Objectivity", 
    "Verism", "Hyperrealism", "Photorealism", "Minimalism", 
    "Color Field Painting", "Post-Painterly Abstraction", "Hard-Edge Painting", "Lyrical Abstraction", 
    "Pattern and Decoration", "New Realism", "Arte Povera", "Neo-Conceptual Art", 
    "Transavantgarde", "Neo-Expressionism", "Fluxus", "Happenings", 
    "Land Art", "Earthworks", "Site-Specific Art", "Street Art", 
    "Graffiti Art", "Stencil Art", "Yarn Bombing", "Video Game Art", 
    "Game Art", "Data Art", "Generative Art", "Digital Art", 
    "Net Art", "Post-Internet Art", "Bio Art", "Sound Art", 
    "Interactive Art", "Mixed Media Art", "Multimedia Art", "Virtual Reality Art", 
    "Conceptual Art", "Process Art", "Systems Art", "Performance Art", 
    "Body Art", "Fluxus", "Happenings", "Installation Art", 
    "Neo-Dada", "Neoism", "Remodernism", "New European Painting", 
    "Lowbrow", "Pop Surrealism", "Street Art", "Urban Art", 
    "Contemporary Indigenous Australian Art", "Contemporary Inuit Art", "Contemporary Native American Art", "Contemporary Latin American Art", 
    "Contemporary African Art", "Contemporary Middle Eastern Art", "Contemporary Southeast Asian Art", "Contemporary East Asian Art", 
    "Contemporary South Asian Art", "Contemporary Central Asian Art", "Contemporary Oceanian Art", "Contemporary Australian Art", 
    "Contemporary Antarctic Art", "Ephemeral Art", "Environmental Art", "Sustainable Art",
    "Neo-Pop", "Post-Minimalism", "Neo-Fauvism", "Neo-Geometric Conceptualism", 
    "Relational Art", "Social Practice Art", "Intervention Art", "Participatory Art", 
    "Dialogical Art", "Relational Aesthetics", "Environmental Art", "Sustainable Art", 
    "Sculpture Parks", "Kinetic Art", "Op Art", "Concrete Art", 
    "Op-Geo Art", "Conceptual Photography", "Process Photography", "Straight Photography", 
    "New Topographics", "Neo-Futurism", "Retrofuturism", "Cyberpunk Art", 
    "Steampunk Art", "Biopunk Art", "Dieselpunk Art", "Atompunk Art", 
    "Solarpunk Art", "Afrofuturism", "Cybernetic Art", "Postmodern Art", 
    "Deconstructivism", "Remodernism", "Digital Realism", "Metamodernism", 
    "Quantum Realism", "Stuckism", "Abject Art", "Feminist Art", 
    "Queer Art", "LGBTQ+ Art", "Identity Art", "Postcolonial Art", 
    "Afrocentric Art", "Asian-American Art", "Indigenous Art", "Global Art", 
    "Post-Internet Art", "Glitch Art", "Vaporwave Art", "Tumblr Art", 
    "Meme Art", "Emoji Art", "Algorithmic Art", "Generative Adversarial Network (GAN) Art", 
    "Crypto Art", "NFT Art", "Augmented Reality (AR) Art", "Virtual Reality (VR) Art", 
    "Immersive Art", "Projection Mapping", "Light Art", "Neon Art", 
    "Bioluminescent Art", "Dark Art", "Macabre Art", "Gothic Art", 
    "Horror Art", "Fantasy Art", "Sci-Fi Art", "Dystopian Art", 
    "Utopian Art", "Speculative Fiction Art", "Mythopoeic Art", "Fantastique Art", 
    "New Media Art", "Postdigital Art", "Algorithmic Art", "Algorithmic Trading Art", 
    "Data Visualization Art", "Artificial Intelligence (AI) Art", "Robotics Art", "Biorobotics Art", 
    "Augmented Reality (AR) Art", "Virtual Reality (VR) Art", "Immersive Art", "Projection Mapping", 
    "Holographic Art", "Quantum Art", "Nanotechnology Art", "BioArt", 
    "Quantum Art", "Post-Quantum Art", "Cosmic Art", "Astro Art", 
    "Space Art", "Exoplanetary Art", "Extraterrestrial Art", "Astrobiology Art"
    "Holopunk Art", "Solarpunk Art", "Oceanpunk Art", "Ecopunk Art", 
    "Biopunk Art", "Feminist Sci-Fi Art", "Afrofuturist Sci-Fi Art", "Cyberfeminist Art", 
    "Tech Noir Art", "Neon Noir Art", "Solar Noir Art", "Cyber Noir Art", 
    "Biomechanical Art", "Bio-Mechanical Hybrid Art", "Cybernetic Organism (Cyborg) Art", "Posthumanist Art", 
    "Transhumanist Art", "Post-Singularity Art", "Dark Web Art", "Crypto Anarchy Art", 
    "Post-Capitalist Art", "Post-Socialist Art", "Post-Communist Art", "Post-Colonial Art", 
    "Post-Military Dictatorship Art", "Post-Apocalyptic Art", "Climate Fiction Art", "Climate Crisis Art", 
    "Apocalyptic Art", "Eco-Dystopian Art", "Eco-Utopian Art", "Eco-Surrealist Art", 
    "Apophenic Art", "Psychedelic Art", "Visionary Art", "Entoptic Art", 
    "Dazzle Camouflage Art", "Bioinformatics Art", "Genetic Art", "Synthetic Biology Art", 
    "Biodesign Art", "Environmental Genetics Art", "Post-Human Genetics Art", "Cosmoecological Art", 
    "Quantum Computing Art", "Quantum Cryptography Art", "Quantum Resistance Art", "Quantum Communication Art", 
    "Quantum Internet Art", "Quantum Encryption Art", "Quantum Entanglement Art", "Quantum Consciousness Art", 
    "Post-Quantum Computing Art", "Post-Quantum Cryptography Art", "Post-Quantum Resistance Art", "Post-Quantum Communication Art", 
    "Post-Quantum Internet Art", "Post-Quantum Encryption Art", "Post-Quantum Entanglement Art", "Post-Quantum Consciousness Art", 
    "Neural Network Art", "Generative Adversarial Network (GAN) Art", "Deepfake Art", "Neuroaesthetics Art", 
    "Biomimetic Art", "Crustacean Aesthetic Art", "Lichen Aesthetic Art", "Moss Aesthetic Art", 
    "Aerogel Aesthetic Art", "Astrobiology Art", "Exoplanetary Astrobiology Art", "Extraterrestrial Astrobiology Art", 
    "Cosmic Evolution Art", "Astroecology Art", "Astroethics Art", "Astropolitics Art", 
    "Astrosociology Art", "Astroaesthetics Art", "Exoplanetary Geology Art", "Extraterrestrial Geology Art", 
    "Cosmic Paleontology Art", "Astroanthropology Art", "Astrobiology Art", "Astrogeology Art", 
    "Astrocartography Art", "Astrophotography Art", "Astroart History", "Astroart Criticism", 
    "Quantum Entanglement Art", "Quantum Consciousness Art", "Quantum Realism", "Quantum Expressionism", 
    "Quantum Impressionism", "Quantum Abstraction", "Quantum Figurativism", "Quantum Symbolism", 
    "Quantum Cubism", "Quantum Surrealism", "Quantum Dadaism", "Quantum Futurism", 
    "Quantum Minimalism", "Quantum Post-Minimalism", "Quantum Abstract Illusionism", "Quantum Social Realism", 
    "Quantum Romanticism", "Quantum Symbolism", "Quantum Aestheticism", "Quantum Decadence", 
    "Quantum Neo-Rococo", "Quantum Neoclassicism", "Quantum Neo-Baroque", "Quantum Neo-Gothic", 
    "Quantum Afrofuturism", "Quantum Cyberpunk Art", "Quantum Biopunk Art", "Quantum Solarpunk Art", 
    "Quantum Ecopunk Art", "Quantum Steampunk Art", "Quantum Retrofuturism", "Quantum Gothic Art", 
    "Quantum Utopian Art", "Quantum Dystopian Art", "Quantum Transhumanist Art", "Quantum Posthumanist Art", 
    "Quantum Cyberfeminist Art", "Quantum Tech Noir Art", "Quantum Postmodern Art", "Quantum Deconstructivism", 
    "Quantum Remodernism", "Quantum Digital Realism", "Quantum Metamodernism", "Quantum Post-Quantum Art", 
    "Quantum Apocalyptic Art", "Quantum Eco-Dystopian Art", "Quantum Eco-Utopian Art", "Quantum Eco-Surrealist Art", 
    "Quantum Apophenic Art", "Quantum Psychedelic Art", "Quantum Visionary Art", "Quantum Entoptic Art", 
    "Quantum Dazzle Camouflage Art", "Quantum Bioinformatics Art", "Quantum Genetic Art", "Quantum Synthetic Biology Art", 
    "Quantum Biodesign Art", "Quantum Environmental Genetics Art", "Quantum Post-Human Genetics Art", "Quantum Cosmoecological Art", 
    "Quantum Post-Quantum Computing Art", "Quantum Post-Quantum Cryptography Art", "Quantum Post-Quantum Resistance Art", "Quantum Post-Quantum Communication Art", 
    "Quantum Post-Quantum Internet Art", "Quantum Post-Quantum Encryption Art", "Quantum Post-Quantum Entanglement Art", "Quantum Post-Quantum Consciousness Art", 
    "Quantum Neural Network Art", "Quantum Generative Adversarial Network (GAN) Art", "Quantum Deepfake Art", "Quantum Neuroaesthetics Art", 
    "Quantum Biomimetic Art", "Quantum Crustacean Aesthetic Art", "Quantum Lichen Aesthetic Art", "Quantum Moss Aesthetic Art", 
    "Quantum Aerogel Aesthetic Art", "Quantum Astrobiology Art", "Quantum Exoplanetary Astrobiology Art", "Quantum Extraterrestrial Astrobiology Art", 
    "Quantum Cosmic Evolution Art", "Quantum Astroecology Art", "Quantum Astroethics Art", "Quantum Astropolitics Art", 
    "Quantum Astrosociology Art", "Quantum Astroaesthetics Art", "Quantum Exoplanetary Geology Art", "Quantum Extraterrestrial Geology Art", 
    "Quantum Cosmic Paleontology Art", "Quantum Astroanthropology Art", "Quantum Astrobiology Art", "Quantum Astrogeology Art", 
    "Quantum Astrocartography Art", "Quantum Astrophotography Art", "Quantum Astroart History", "Quantum Astroart Criticism", 
        #################   top-100-most-famous-artists   ########################
    "Pablo Picasso", "Giotto di Bondone", "Leonardo da Vinci", "Paul Cézanne", 
    "Rembrandt van Rijn", "Diego Velázquez", "Wassily Kandinsky", "Claude Monet", 
    "Michelangelo", "Francis Bacon", "Edgar Degas", "Hans Holbein", "Vincent Van Gogh", 
    "Edgar Degas", "Gustav Klimt", "Henri Matisse", "Pierre-Auguste Renoir", 
    "Joseph Albers", "Albrecht Altdorfer", "Giuseppe Arcimboldo", 
    "Salvador Dalí", "Max Ernst", "Frida Kahlo", "Henri Rousseau",
    "Georgia O'Keeffe", "Edward Hopper", "Andy Warhol",
    "Roy Lichtenstein", "Hans Hoffman", "Willem de Kooning",
    "Arshile Gorky", "Franz Kline", "Mark Rothko",
    "Jackson Pollock", "Piet Mondrian", "Joan Miro", "Marc Chagall",
    "Kazimir Malevich", "Egon Schiele", "Edvard Munch", "Auguste Rodin",
    "Gustave Moreau", "Paul Gauguin", "Georges Seurat", "Pierre Puvis de Chavannes",
    "Édouard Manet", "James McNeill Whistler", "Dante Gabriel Rossetti",
    "Jean François Millet", "Honoré Daumier", 
    "Claude Lorrain", "Nicolas Poussin", "Titian", "Johannes Vermeer",
    "Raphael", "Caravaggio", "Peter Paul Rubens", "Jan van Eyck",
    "Georges Braque", "Paul Klee", "Alberto Giacometti", "Balthus",
    "Amedeo Modigliani", "Jean-Michel Basquiat", "Lucian Freud", "Frank Stella",
    "Agnes Martin", "Marcel Duchamp", "Jackson Pollock", "Yves Klein",
    "Gerhard Richter", "Anselm Kiefer", "Kazuo Shiraga", "Clyfford Still",
    "Philip Guston", "Sol LeWitt", "Cy Twombly", "Robert Rauschenberg",
    "Jasper Johns", "Yayoi Kusama", "Louise Bourgeois", "Richard Serra",
    "Damien Hirst", "Banksy", "Yoko Ono", "Jenny Holzer",
    "Jeff Koons", "Keith Haring", "Marina Abramović", "David Hockney",
    "Ai Weiwei", "Bridget Riley", "Chuck Close", "Kara Walker",
    "Takashi Murakami", "Cindy Sherman", "Gilbert & George", "Hokusai",
    "Käthe Kollwitz", "Tamara de Lempicka", "Amedeo Modigliani", "Fernand Léger",
    "Winslow Homer", "Grant Wood", "Edward Steichen", "Walker Evans",
    "Dorothea Lange", "Edward Weston", "Man Ray", "Clement Greenberg",
    "Harold Rosenberg", "Frank Lloyd Wright", "Le Corbusier", "Eero Saarinen",
    "Zaha Hadid", "I. M. Pei", "Rem Koolhaas", "Frank Gehry",
    "Renzo Piano", "Jean Nouvel", "Richard Meier", "Peter Zumthor",
    "Alvar Aalto", "Louis Kahn", "Daniel Libeskind", "Norman Foster",
    "Tadao Ando", "Frank Lloyd Wright", "Le Corbusier", "Eero Saarinen",
    "Zaha Hadid", "I. M. Pei", "Rem Koolhaas", "Frank Gehry",
    "Renzo Piano", "Jean Nouvel", "Richard Meier", "Peter Zumthor",
     "Hans Arp", "Giovanni Bellini", "Sandro Botticelli", "Pieter Bruegel the Elder", 
    "Alexander Calder", "Marc Chagall", "William Merritt Chase", "Giorgio de Chirico", 
    "John Constable", "Lucas Cranach the Elder", "Salvador Dalí", "Honoré Daumier", 
    "Stuart Davis", "Edgar Degas", "Robert Delaunay", "André Derain", 
    "Albrecht Dürer", "Thomas Eakins", "Albert Eckhout", "Max Ernst", 
    "Jasper Francis Cropsey", "Lucas Cranach the Younger", "Eugène Delacroix", "Edgar Degas", 
    "Otto Dix", "Jean Dubuffet", "Thomas Eakins", "El Greco", 
    "James Ensor", "Max Ernst", "Sir Jacob Epstein", "Philip Evergood", 
    "George Grosz", "Giovanni Battista Gaulli", "Jean-Léon Gérôme", "Alberto Giacometti", 
    "Giorgione", "Arshile Gorky", "George Grosz", "Frans Hals", 
    "Winslow Homer", "Edward Hopper", "William Holman Hunt", "Amedeo Modigliani", 
    "Jean-Auguste-Dominique Ingres", "Jusepe de Ribera", "Angelica Kauffman", "Barnett Newman", 
    "Sir Joshua Reynolds", "Pierre-Auguste Renoir", "George Romney", "Henri Rousseau", 
    "Peter Paul Rubens", "John Singer Sargent", "Chaim Soutine", "Max Weber", 
    "James McNeill Whistler", "Grant Wood", "Andrew Wyeth", "Carlos Almaraz", 
    "Bas Jan Ader", "John Altoon", "Leonor Fini", "Gérard Fromanger", 
    "Hans Hofmann", "Eva Hesse", "Jean-Pierre Hoschedé", "Howard Hodgkin", 
    "Jörg Immendorff", "Ralph Inge", "Roberto Matta", "Joan Mitchell", 
    "Amedeo Modigliani", "Robert Motherwell", "Alice Neel", "Louise Nevelson", 
    "Barnett Newman", "Elie Nadelman", "David Park", "Giuseppe Penone", 
    "Irving Penn", "Eduardo Paolozzi", "Eduardo Souto de Moura", "Esteban Vicente", 
    "Herman van Swanevelt", "Victor Vasarely", "Vieira da Silva", "Sylvester Vitali", 
    "Johannes Voet", "Emil Volkers", "Maurice de Vlaminck", "Carlos Páez Vilaró", 
    "Pierre Puvis de Chavannes", "Jean-Pierre Pincemin", "Krzysztof Penderecki", "Giovanni Paolo Pannini", 
    "Nam June Paik", "Meret Oppenheim", "Julian Onderdonk", "Claes Oldenburg", 
    "Dennis Oppenheim", "Camille Pissarro", "Giovanni Battista Piranesi", "Ilya Repin", 
    "Pierre-Auguste Renoir", "Diego Rivera", "Larry Rivers", "Waldo Pierce", 
    "Lydia Plavin", "Horace Pippin", "Amédée Ozenfant", "Germaine Richier", 
    "Alexandre Rodchenko", "Oscar Rabin", "Auguste Rodin", "George Rickey", 
    "Larry Rivers", "Robert Rauschenberg", "Odilon Redon", "Rembrandt Harmenszoon van Rijn", 
    "Pierre-Auguste Renoir", "Jusepe de Ribera", "John Ruskin", "Diego Rivera", 
    "Gerhard Richter", "Larry Rivers", "Auguste Rodin", "Michelangelo Buonarroti", 
    "Mark Rothko", "Betye Saar", "Yves Saint Laurent", "Egon Schiele", 
    "Gino Severini", "Cindy Sherman", "David Alfaro Siqueiros", "Chaim Soutine", 
    "Pat Steir", "Frank Stella", "Joseph Stella", "Daniel Spoerri", 
    "Hans-Joachim Stuck", "Philip Guston", "John Tenniel", "James Tissot", 
    "Jacopo Tintoretto", "Henri de Toulouse-Lautrec", "Ettore Sottsass", "Yves Tanguy", 
    "Alma Thomas", "Federico Zuccari", "Francisco Zúñiga", "Jack Zajac", 
    "Zhang Daqian", "Zhang Hongtu", "Francesco Zuccarelli", "Andrea Zucchi", 
    "Zao Wou-Ki", "Paul Éluard", "Julio Galán", "Joseph Goldyne", 
    "Yoko Ono", "Elaine Sturtevant", "Rem Koolhaas", "Jean Nouvel", 
    "Richard Meier", "Peter Zumthor", "Santiago Calatrava", "David Hockney", 
    "Ai Weiwei", "Bridget Riley", "Chuck Close", "Kara Walker", 
    "Takashi Murakami", "Cindy Sherman", "Gilbert & George", "Hokusai", 
    "Käthe Kollwitz", "Tamara de Lempicka", "Amedeo Modigliani", "Fernand Léger", 
    "Winslow Homer", "Grant Wood", "Edward Steichen", "Walker Evans", 
    "Dorothea Lange", "Edward Weston", "Man Ray", "Clement Greenberg", 
    "Harold Rosenberg", "Frank Lloyd Wright", "Le Corbusier", "Eero Saarinen", 
    "Zaha Hadid", "I. M. Pei", "Rem Koolhaas", "Frank Gehry", 
    "Renzo Piano", "Jean Nouvel", "Richard Meier", "Peter Zumthor",
    "Ivan Aivazovsky", "Abdulqader Al Rais", "Francis Alÿs", "David Annesley", 
    "István Csók", "Ignacio Zuloaga", "Emil Nolde", "John Bauer", 
    "František Kupka", "Paul Serusier", "Alexandre Benois", "Gustaf Cederström", 
    "Johan Axel Gustaf Acke", "Eero Järnefelt", "Akseli Gallen-Kallela", "Helene Schjerfbeck", 
    "Hugo Simberg", "Félix Vallotton", "Ferdinand Hodler", "Félix Vallotton", 
    "Édouard Vuillard", "Koloman Moser", "Gustav Klimt", "Egon Schiele", 
    "Oskar Kokoschka", "Richard Gerstl", "Kazimir Malevich", "Pavel Filonov", 
    "Marc Chagall", "Kasimir Malevich", "Ilya Repin", "Wassily Kandinsky", 
    "Alexandra Exter", "Lyubov Popova", "Varvara Stepanova", "Natalia Goncharova", 
    "Kazimir Malevich", "El Lissitzky", "László Moholy-Nagy", "Kurt Schwitters", 
    "Max Ernst", "Hannah Höch", "Otto Dix", "George Grosz", 
    "John Heartfield", "André Masson", "René Magritte", "Giorgio de Chirico", 
    "Max Ernst", "Salvador Dalí", "Joan Miró", "Yves Tanguy", 
    "Paul Delvaux", "Frida Kahlo", "Diego Rivera", "David Alfaro Siqueiros", 
    "José Clemente Orozco", "Wifredo Lam", "Roberto Matta", "Rufino Tamayo", 
    "Tamara de Lempicka", "Amedeo Modigliani", "Umberto Boccioni", "Giacomo Balla", 
    "Carlo Carrà", "Luigi Russolo", "Gino Severini", "Kazimir Malevich", 
    "Vladimir Tatlin", "Alexander Rodchenko", "El Lissitzky", "Naum Gabo", 
    "Antoine Pevsner", "Fernand Léger", "Juan Gris", "Francis Picabia", 
    "Albert Gleizes", "Jean Metzinger", "Robert Delaunay", "Sonia Delaunay", 
    "Gino Severini", "Umberto Boccioni", "Carlo Carrà", "Luigi Russolo", 
    "Giacomo Balla", "Fortunato Depero", "Amédée Ozenfant", "Le Corbusier", 
    "Fernand Léger", "Jean Hélion", "Alberto Magnelli", "Kurt Schwitters", 
    "Hannah Höch", "Raoul Hausmann", "Hugo Ball", "Emmy Hennings", 
    "Richard Huelsenbeck", "John Heartfield", "George Grosz", "Hans Arp", 
    "Max Ernst", "Marcel Duchamp", "Man Ray", "Francis Picabia", 
    "Pablo Picasso", "Georges Braque", "Juan Gris", "Fernand Léger", 
    "André Masson", "Joan Miró", "Yves Tanguy", "Max Ernst", 
    "Paul Klee", "Kurt Schwitters", "Hans Arp", "Jean (Hans) Arp", 
    "Sophie Taeuber-Arp", "Alberto Giacometti", "Jean (Hans) Arp", "Fernand Léger", 
    "Naum Gabo", "Antoine Pevsner", "Alexander Calder", "Vladimir Tatlin", 
    "El Lissitzky", "Kazimir Malevich", "Lyubov Popova", "Varvara Stepanova", 
    "Natalia Goncharova", "Wassily Kandinsky", "Paul Klee", "Alexandra Exter", 
    "Marc Chagall", "Chaim Soutine", "Kazimir Malevich", "Wassily Kandinsky", 
    "Piet Mondrian", "Theo van Doesburg", "Bart van der Leck", "Gerrit Rietveld", 
    "Georges Vantongerloo", "Jean Gorin", "Auguste Herbin", "Fernand Léger", 
    "Albert Gleizes", "Robert Delaunay", "Sonia Delaunay", "Fernand Léger", 
    "Juan Gris", "Francis Picabia", "Albert Gleizes", "Jean Metzinger", 
    "Robert Delaunay", "Sonia Delaunay", "Gino Severini", "Umberto Boccioni", 
    "Carlo Carrà", "Luigi Russolo", "Giacomo Balla", "Fortunato Depero", 
    "Amédée Ozenfant", "Le Corbusier", "Fernand Léger", "Jean Hélion", 
    "Alberto Magnelli", "Kurt Schwitters", "Hannah Höch", "Raoul Hausmann", 
    "Hugo Ball", "Emmy Hennings", "Richard Huelsenbeck", "John Heartfield", 
    "George Grosz", "Hans Arp", "Max Ernst", "Marcel Duchamp", 
    "Man Ray", "Francis Picabia", "Pablo Picasso", "Georges Braque", 
    "Juan Gris", "Fernand Léger", "André Masson", "Joan Miró", 
    "Yves Tanguy", "Max Ernst", "Paul Klee", "Kurt Schwitters", 
    "Hans Arp", "Jean (Hans) Arp", "Sophie Taeuber-Arp", "Alberto Giacometti", 
    "Jean (Hans) Arp", "Fernand Léger", "Naum Gabo", "Antoine Pevsner", 
    "Alexander Calder", "Vladimir Tatlin", "El Lissitzky", "Kazimir Malevich", 
    "Lyubov Popova", "Varvara Stepanova", "Natalia Goncharova", "Wassily Kandinsky", 
    "Paul Klee", "Alexandra Exter", "Marc Chagall", "Chaim Soutine", 
    "Kazimir Malevich", "Wassily Kandinsky", "Piet Mondrian", "Theo van Doesburg", 
    "Bart van der Leck", "Gerrit Rietveld", "Georges Vantongerloo", "Jean Gorin", 
    "Auguste Herbin", "Fernand Léger", "Albert Gleizes", "Robert Delaunay", 
    "Sonia Delaunay", "Fernand Léger", "Juan Gris", "Francis Picabia", 
    "Albert Gleizes", "Jean Metzinger", "Robert Delaunay", "Sonia Delaunay", 
    "Gino Severini", "Umberto Boccioni", "Carlo Carrà", "Luigi Russolo", 
    "Giacomo Balla", "Fortunato Depero", "Amédée Ozenfant", "Le Corbusier", 
    "Fernand Léger", "Jean Hélion", "Alberto Magnelli", "Kurt Schwitters", 
    "Hannah Höch", "Raoul Hausmann", "Hugo Ball", "Emmy Hennings", 
    "Richard Huelsenbeck", "John Heartfield", "George Grosz", "Hans Arp", 
    "Max Ernst", "Marcel Duchamp", "Man Ray", "Francis Picabia", 
    "Pablo Picasso", "Georges Braque", "Juan Gris", "Fernand Léger", 
    "André Masson", "Joan Miró", "Yves Tanguy", "Max Ernst", 
    "Paul Klee", "Kurt Schwitters", "Hans Arp", "Jean (Hans) Arp", 
    "Sophie Taeuber-Arp", "Alberto Giacometti", "Jean (Hans) Arp", "Fernand Léger", 
    "Naum Gabo", "Antoine Pevsner", "Alexander Calder", "Vladimir Tatlin", 
    "El Lissitzky", "Kazimir Malevich", "Lyubov Popova", "Varvara Stepanova", 
    "Natalia Goncharova", "Wassily Kandinsky", "Paul Klee", "Alexandra Exter", 
    "Marc Chagall", "Chaim Soutine", "Kazimir Malevich", "Wassily Kandinsky", 
    "Piet Mondrian", "Theo van Doesburg", "Bart van der Leck", "Gerrit Rietveld", 
    "Georges Vantongerloo", "Jean Gorin", "Auguste Herbin", "Fernand Léger", 
    "Albert Gleizes", "Robert Delaunay", "Sonia Delaunay", "Fernand Léger", 
    "Juan Gris", "Francis Picabia", "Albert Gleizes", "Jean Metzinger", 
    "Robert Delaunay", "Sonia Delaunay", "Gino Severini", "Umberto Boccioni", 
    "Carlo Carrà", "Luigi Russolo", "Giacomo Balla", "Fortunato Depero", 
    "Amédée Ozenfant", "Le Corbusier", "Fernand Léger", "Jean Hélion", 
    "Alberto Magnelli", "Kurt Schwitters", "Hannah Höch", "Raoul Hausmann", 
    "Hugo Ball", "Emmy Hennings", "Richard Huelsenbeck", "John Heartfield", 
    "George Grosz", "Hans Arp", "Max Ernst", "Marcel Duchamp", 
    "Man Ray", "Francis Picabia", "Pablo Picasso", "Georges Braque", 
    "Juan Gris", "Fernand Léger", "André Masson", "Joan Miró", 
    "Yves Tanguy", "Max Ernst", "Paul Klee", "Kurt Schwitters", 
    "Hans Arp", "Jean (Hans) Arp", "Sophie Taeuber-Arp", "Alberto Giacometti", 
    "Jean (Hans) Arp", "Fernand Léger", "Naum Gabo", "Antoine Pevsner", 
    "Alexander Calder", "Vladimir Tatlin", "El Lissitzky", "Kazimir Malevich", 
    "Lyubov Popova", "Varvara Stepanova", "Natalia Goncharova", "Wassily Kandinsky", 
    "Paul Klee", "Alexandra Exter", "Marc Chagall", "Chaim Soutine", 
    "Kazimir Malevich", "Wassily Kandinsky", "Piet Mondrian", "Theo van Doesburg", 
    "Bart van der Leck", "Gerrit Rietveld",
        #################   representative-works   ########################
    "Les Demoiselles d'Avignon by Pablo Picasso", "Guernica by Pablo Picasso", "The Weeping Woman by Pablo Picasso",
    "The Ognissanti Madonna by Giotto di Bondone", "The Last Judgment by Giotto di Bondone", "The Arena Chapel frescoes by Giotto di Bondone",
    "Mona Lisa by Leonardo da Vinci", "The Last Supper by Leonardo da Vinci", "Vitruvian Man by Leonardo da Vinci",
    "The Card Players by Paul Cézanne", "Mont Sainte-Victoire by Paul Cézanne", "Still Life with Apples by Paul Cézanne",
    "The Night Watch by Rembrandt van Rijn", "The Anatomy Lesson of Dr. Nicolaes Tulp by Rembrandt van Rijn", "Self-Portrait with Two Circles by Rembrandt van Rijn",
    "Las Meninas by Diego Velázquez", "The Surrender of Breda by Diego Velázquez", "Portrait of Pope Innocent X by Diego Velázquez",
    "Black Square by Kazimir Malevich", "White on White by Kazimir Malevich", "Suprematist Composition: White on White by Kazimir Malevich",
    "Water Lilies series by Claude Monet", "Impression, Sunrise by Claude Monet", "Woman with a Parasol by Claude Monet",
    "David by Michelangelo", "The Creation of Adam by Michelangelo", "The Pieta by Michelangelo",
    "Study after Velázquez's Portrait of Pope Innocent X by Francis Bacon", "Three Studies for Figures at the Base of a Crucifixion by Francis Bacon", "Portrait of George Dyer in a Mirror by Francis Bacon",
    "The Starry Night by Vincent Van Gogh", "Sunflowers by Vincent Van Gogh", "Cafe Terrace at Night by Vincent Van Gogh",
    "The Little Fourteen-Year-Old Dancer by Edgar Degas", "The Dance Class by Edgar Degas", "L'Absinthe by Edgar Degas",
    "The Ambassadors by Hans Holbein", "Portrait of Henry VIII by Hans Holbein", "Christina of Denmark, Duchess of Milan by Hans Holbein",
    "Starry Night by Vincent Van Gogh", "Sunflowers by Vincent Van Gogh", "Cafe Terrace at Night by Vincent Van Gogh",
    "The Kiss by Gustav Klimt", "Portrait of Adele Bloch-Bauer I by Gustav Klimt", "The Tree of Life by Gustav Klimt",
    "The Dance by Henri Matisse", "Woman with a Hat by Henri Matisse", "The Joy of Life by Henri Matisse",
    "Bal du Moulin de la Galette by Pierre-Auguste Renoir", "Luncheon of the Boating Party by Pierre-Auguste Renoir", "Dance at Le Moulin de la Galette by Pierre-Auguste Renoir",
    "Homage to the Square series by Joseph Albers", "Interaction of Color by Joseph Albers", "Homage to the Square: Apparition by Joseph Albers",
    "The Battle of Alexander at Issus by Albrecht Altdorfer", "Danube Landscape near Regensburg by Albrecht Altdorfer", "The Birth of John the Baptist by Albrecht Altdorfer",
    "The Librarian by Giuseppe Arcimboldo", "Vertumnus by Giuseppe Arcimboldo", "The Jurist by Giuseppe Arcimboldo",
    "The Persistence of Memory by Salvador Dalí", "The Elephants by Salvador Dalí", "Christ of Saint John of the Cross by Salvador Dalí",
    "The Elephant Celebes by Max Ernst", "The Horde by Max Ernst", "The Robing of the Bride by Max Ernst",
    "The Two Fridas by Frida Kahlo", "Self-Portrait with Thorn Necklace and Hummingbird by Frida Kahlo", "The Broken Column by Frida Kahlo",
    "The Sleeping Gypsy by Henri Rousseau", "The Dream by Henri Rousseau", "The Snake Charmer by Henri Rousseau",
    "Sky Above Clouds IV by Georgia O'Keeffe", "Black Iris by Georgia O'Keeffe", "Cow's Skull: Red, White, and Blue by Georgia O'Keeffe",
    "Nighthawks by Edward Hopper", "Automat by Edward Hopper", "Office at Night by Edward Hopper",
    "Campbell's Soup Cans by Andy Warhol", "Marilyn Diptych by Andy Warhol", "Eight Elvises by Andy Warhol",
    "Drowning Girl by Roy Lichtenstein", "Whaam! by Roy Lichtenstein", "Oh, Jeff... I Love You, Too... But... by Roy Lichtenstein",
    "Autumn Gold by Hans Hofmann", "The Gate by Hans Hofmann", "Spring by Hans Hofmann",
    "Woman I by Willem de Kooning", "Excavation by Willem de Kooning", "Marilyn Monroe by Willem de Kooning",
    "The Artist and His Mother by Arshile Gorky", "The Liver is the Cock's Comb by Arshile Gorky", "Water of the Flowery Mill by Arshile Gorky",
    "Chief by Franz Kline", "Mahoning by Franz Kline", "C & O by Franz Kline",
    "No. 61 (Rust and Blue) by Mark Rothko", "White Center (Yellow, Pink and Lavender on Rose) by Mark Rothko", "Untitled (Black on Gray) by Mark Rothko",
    "Autumn Rhythm (Number 30) by Jackson Pollock", "No. 5, 1948 by Jackson Pollock", "Lavender Mist by Jackson Pollock",
    "Composition with Red, Yellow, and Blue by Piet Mondrian", "Broadway Boogie Woogie by Piet Mondrian", "Composition A by Piet Mondrian",
    "The Tilled Field by Joan Miró", "The Birth of the World by Joan Miró", "Woman and Bird in the Moonlight by Joan Miró",
    "I and the Village by Marc Chagall", "The Birthday by Marc Chagall", "The Green Violinist by Marc Chagall",
    "Black Square by Kazimir Malevich", "White on White by Kazimir Malevich", "Suprematist Composition: White on White by Kazimir Malevich",
    "The Kiss by Egon Schiele", "Portrait of Edith Schiele by Egon Schiele", "Self-Portrait with Physalis by Egon Schiele",
    "The Scream by Edvard Munch", "The Madonna by Edvard Munch", "The Dance of Life by Edvard Munch",
    "The Thinker by Auguste Rodin", "The Kiss by Auguste Rodin", "The Burghers of Calais by Auguste Rodin",
    "The Apparition by Gustave Moreau", "Jupiter and Semele by Gustave Moreau", "The Chimera by Gustave Moreau",
    "Where Do We Come From? What Are We? Where Are We Going? by Paul Gauguin", "The Yellow Christ by Paul Gauguin", "Tahitian Women on the Beach by Paul Gauguin",
    "A Sunday Afternoon on the Island of La Grande Jatte by Georges Seurat", "Bathers at Asnières by Georges Seurat", "Circus Sideshow by Georges Seurat",
    "The Poor Fisherman by Pierre Puvis de Chavannes", "Hope by Pierre Puvis de Chavannes", "The Sacred Grove by Pierre Puvis de Chavannes",
    "Olympia by Édouard Manet", "Luncheon on the Grass by Édouard Manet", "A Bar at the Folies-Bergère by Édouard Manet",
    "Arrangement in Grey and Black No. 1 (Whistler's Mother) by James McNeill Whistler", "Nocturne in Black and Gold: The Falling Rocket by James McNeill Whistler", "Symphony in White, No. 1: The White Girl by James McNeill Whistler",
    "Beata Beatrix by Dante Gabriel Rossetti", "Proserpine by Dante Gabriel Rossetti", "Lady Lilith by Dante Gabriel Rossetti",
    "The Gleaners by Jean François Millet", "The Angelus by Jean François Millet", "The Sower by Jean François Millet",
    "The Third-Class Carriage by Honoré Daumier", "Gargantua by Honoré Daumier", "Ratapoil by Honoré Daumier", 
    "Landscape with Cephalus and Procris reunited by Claude Lorrain", "The Enchanted Castle by Claude Lorrain", "Apollo and the Muses on Mount Helicon by Claude Lorrain",
    "The Death of Germanicus by Nicolas Poussin", "The Rape of the Sabine Women by Nicolas Poussin", "Et in Arcadia Ego by Nicolas Poussin",
    "Venus of Urbino by Titian", "Bacchus and Ariadne by Titian", "The Assumption of the Virgin by Titian",
    "Girl with a Pearl Earring by Johannes Vermeer", "The Milkmaid by Johannes Vermeer", "The Art of Painting by Johannes Vermeer",
    "The School of Athens by Raphael", "The Sistine Madonna by Raphael", "The Marriage of the Virgin by Raphael",
    "The Calling of Saint Matthew by Caravaggio", "Judith Beheading Holofernes by Caravaggio", "The Supper at Emmaus by Caravaggio",
    "The Elevation of the Cross by Peter Paul Rubens", "The Garden of Love by Peter Paul Rubens", "The Descent from the Cross by Peter Paul Rubens",
    "The Arnolfini Portrait by Jan van Eyck", "The Ghent Altarpiece by Jan van Eyck", "The Madonna with Canon van der Paele by Jan van Eyck",
    "Houses at L'Estaque by Georges Braque", "Violin and Candlestick by Georges Braque", "Woman with a Guitar by Georges Braque",
    "Senecio by Paul Klee", "Fish Magic by Paul Klee", "Ad Parnassum by Paul Klee",
    "Walking Man I by Alberto Giacometti", "The Palace at 4 a.m. by Alberto Giacometti", "City Square by Alberto Giacometti",
    "The King by Balthus", "The Room by Balthus", "The Street by Balthus",
    "Reclining Nude by Amedeo Modigliani", "Portrait of Jeanne Hébuterne by Amedeo Modigliani", "The Red Head by Amedeo Modigliani",
    "Untitled (Skull) by Jean-Michel Basquiat", "Boy and Dog in a Johnnypump by Jean-Michel Basquiat", "Irony of Negro Policeman by Jean-Michel Basquiat",
    "Benefits Supervisor Sleeping by Lucian Freud", "Girl with a White Dog by Lucian Freud", "Reflection with Two Children (Self-portrait) by Lucian Freud",
    "Die Fahne Hoch! by Frank Stella", "The Marriage of Reason and Squalor by Frank Stella", "Harran II by Frank Stella",
    "Night Sea by Agnes Martin", "With My Back to the World by Agnes Martin", "The Islands by Agnes Martin",
    "Fountain by Marcel Duchamp", "Nude Descending a Staircase, No. 2 by Marcel Duchamp", "The Bride Stripped Bare by Her Bachelors, Even by Marcel Duchamp",
    "Autumn Rhythm (Number 30) by Jackson Pollock", "No. 5, 1948 by Jackson Pollock", "Lavender Mist by Jackson Pollock",
    "Anthropometry of the Blue Period by Yves Klein", "Anthropometry of the Void by Yves Klein", "IKB 79 by Yves Klein",
    "October 18, 1977 by Gerhard Richter", "Betty by Gerhard Richter", "Abstraktes Bild by Gerhard Richter",
    "The Book of Life by Anselm Kiefer", "Breaking of the Vessels by Anselm Kiefer", "Sulamith by Anselm Kiefer",
    "Challenging Mudai by Kazuo Shiraga", "Katsu by Kazuo Shiraga", "Work I by Kazuo Shiraga",
    "1957-D No. 1 by Clyfford Still", "1947-Y-No. 2 by Clyfford Still", "1944-N No. 1 by Clyfford Still",
    "Philip Guston's Palette by Philip Guston", "Beggar's Joys by Philip Guston", "Head and Bottle by Philip Guston",
    "Wall Drawing #260 by Sol LeWitt", "Incomplete Open Cube by Sol LeWitt", "Bands of Color in Four Directions by Sol LeWitt",
    "Leda and the Swan by Cy Twombly", "Untitled (Bolsena) by Cy Twombly", "Hero and Leandro by Cy Twombly",
    "Erased de Kooning Drawing by Robert Rauschenberg", "Canyon by Robert Rauschenberg", "Monogram by Robert Rauschenberg",
    "Flag by Jasper Johns", "Target with Plaster Casts by Jasper Johns", "0 through 9 by Jasper Johns",
    "Infinity Mirrored Room - The Souls of Millions of Light Years Away by Yayoi Kusama", "Pumpkin by Yayoi Kusama", "The Obliteration Room by Yayoi Kusama",
    "Untitled (Spider) by Louise Bourgeois", "Maman by Louise Bourgeois", "The Destruction of the Father by Louise Bourgeois",
    "Tilted Arc by Richard Serra", "One Ton Prop (House of Cards) by Richard Serra", "My Curves Are Not Mad by Richard Serra",
    "The Physical Impossibility of Death in the Mind of Someone Living by Damien Hirst", "For the Love of God by Damien Hirst", "Hymn by Damien Hirst",
    "Girl with a Balloon by Banksy", "Flower Thrower by Banksy", "There Is Always Hope by Banksy",
    "Cut Piece by Yoko Ono", "Wish Tree by Yoko Ono", "Imagine Peace Tower by Yoko Ono",
    "Untitled (Selections from Donald Judd) by Jenny Holzer", "Truisms by Jenny Holzer", "Inflammatory Essays by Jenny Holzer",
    "Rabbit by Jeff Koons", "Balloon Dog (Orange) by Jeff Koons", "Puppy by Jeff Koons",
    "Radiant Child by Keith Haring", "Crack is Wack by Keith Haring", "Untitled (Free South Africa) by Keith Haring",
    "The Artist is Present by Marina Abramović", "Rhythm 0 by Marina Abramović", "The House with the Ocean View by Marina Abramović",
    "A Bigger Splash by David Hockney", "Portrait of an Artist (Pool with Two Figures) by David Hockney", "Mr and Mrs Clark and Percy by David Hockney",
    "Dropping a Han Dynasty Urn by Ai Weiwei", "Sunflower Seeds by Ai Weiwei", "Colored Vases by Ai Weiwei",
    "Movement in Squares by Bridget Riley", "Blaze 1 by Bridget Riley", "Fall by Bridget Riley",
    "Big Self-Portrait by Chuck Close", "Fanny/Fingerpainting by Chuck Close", "Phil/Fingerprint by Chuck Close",
    "Harper's Pictorial History of the Civil War (Annotated) by Kara Walker", "Gone: An Historical Romance of a Civil War as It Occurred b'tween the Dusky Thighs of One Young Negress and Her Heart by Kara Walker", "A Subtlety, or the Marvelous Sugar Baby by Kara Walker",
    "Reversed Double Helix by Takashi Murakami", "My Lonesome Cowboy by Takashi Murakami", "727 by Takashi Murakami",
    "Untitled Film Still #21 by Cindy Sherman", "The Broken Child by Cindy Sherman", "Centerfold by Cindy Sherman",
    "The Singing Sculpture by Gilbert & George", "Living Sculpture by Gilbert & George", "The Nature of Our Looking by Gilbert & George",
    "The Great Wave off Kanagawa by Hokusai", "Thirty-Six Views of Mount Fuji by Hokusai", "Fine Wind, Clear Morning by Hokusai",
    "The Weavers by Käthe Kollwitz", "Death and the Mother by Käthe Kollwitz", "Self-Portrait with Hands on Chest by Käthe Kollwitz",
    "Autoportrait (Tamara in the Green Bugatti) by Tamara de Lempicka", "The Musician by Tamara de Lempicka", "Portrait of Doctor Boucard by Tamara de Lempicka",
    "Reclining Nude on a Red Carpet by Amedeo Modigliani", "Portrait of Jean Cocteau by Amedeo Modigliani", "Jeanne Hébuterne with Hat and Necklace by Amedeo Modigliani",
    "Le Grand Déjeuner by Fernand Léger", "The City by Fernand Léger", "The Mechanic by Fernand Léger",
    "American Gothic by Grant Wood", "Daughters of Revolution by Grant Wood", "Daughters of Revolution by Grant Wood",
    "Flatiron Building, Evening by Edward Steichen", "The Family of Man by Edward Steichen", "Rodin - The Thinker by Edward Steichen",
    "Barn and Clouds by Walker Evans", "Alabama Tenant Farmer Wife by Walker Evans", "Allie Mae Burroughs by Walker Evans",
    "Migrant Mother, Nipomo, California by Dorothea Lange", "White Angel Breadline by Dorothea Lange", "Dust Bowl, Oklahoma by Dorothea Lange",
    "Pepper No. 30 by Edward Weston", "Nude by Edward Weston", "Cabbage Leaf by Edward Weston",
    "Man Ray by Man Ray", "The Lovers by Man Ray", "Noire et blanche by Man Ray",
    "Homage to the Square series by Josef Albers", "Interaction of Color by Josef Albers", "Variant / Adobe by Josef Albers",
    "Art and Culture by Clement Greenberg", "Modernist Painting by Clement Greenberg", "Avant-Garde and Kitsch by Clement Greenberg",
    "The Tradition of the New by Harold Rosenberg", "Art on the Edge and Over by Harold Rosenberg", "The Anxious Object by Harold Rosenberg",
    "Fallingwater by Frank Lloyd Wright", "Guggenheim Museum by Frank Lloyd Wright", "Taliesin West by Frank Lloyd Wright",
    "Villa Savoye by Le Corbusier", "Unité d'Habitation by Le Corbusier", "Notre Dame du Haut by Le Corbusier",
    "Gateway Arch by Eero Saarinen", "TWA Flight Center by Eero Saarinen", "Dulles International Airport by Eero Saarinen",
    "Heydar Aliyev Center by Zaha Hadid", "Guangzhou Opera House by Zaha Hadid", "Vitra Campus by Zaha Hadid",
    "National Congress of Brazil by Oscar Niemeyer", "Serpentine Gallery Pavilion by Oscar Niemeyer", "Cathedral of Brasília by Oscar Niemeyer",
    "Bank of China Tower by I. M. Pei", "Louvre Pyramid by I. M. Pei", "East Building, National Gallery of Art by I. M. Pei",
    "Casa da Música by Rem Koolhaas", "Seattle Central Library by Rem Koolhaas", "CCTV Headquarters by Rem Koolhaas",
    "Guggenheim Museum Bilbao by Frank Gehry", "Walt Disney Concert Hall by Frank Gehry", "Dancing House by Frank Gehry", 
    "The Shard by Renzo Piano", "Centre Georges Pompidou by Renzo Piano", "Whitney Museum of American Art by Renzo Piano",
    "Louvre Abu Dhabi by Jean Nouvel", "Torre Agbar by Jean Nouvel", "One Central Park by Jean Nouvel",
    "Getty Center by Richard Meier", "The Jubilee Church by Richard Meier", "Ara Pacis Museum by Richard Meier",
    "Thermal Bath Vals by Peter Zumthor", "Kolumba Museum by Peter Zumthor", "Bruder Klaus Field Chapel by Peter Zumthor"
]
# text = clip.tokenize(whole_style_list).to(device)
# with open('whole_style_list_tokens.pkl', 'wb') as f:
#     pickle.dump(text, f)
whole_style_list = list(dict.fromkeys(whole_style_list))



anime_style_list = [
 #################   anime-styles   ########################
    "Kawaii", "Chibi", "Moe", "Shonen", "Shojo",
    "Seinen", "Josei", "Kodomomuke", "Realistic", "Cartoonish",
    "1980s", "1990s", "Kemonomimi", "Masaaki Yuasa Works",
    "JoJo's Bizarre Adventure", "Ecchi", "Moe for women",
    "One Piece", "Naruto", "Webtoon", "Retro 80's style", 
    "Donghua", "1980s", "1990s", "Webtoon", "Masaaki Yuasa Works",
    "JoJo's Bizarre Adventure", "Ecchi", "Moe for Women", "Animecore",
    "Classic Proxy", "One Piece Naruto", "Retro 80's Style",
    "Disney Anime Style", "Japan's Rich Folklore Style", "90s Anime Style",
    "2000s Anime Style", "Anime Streetwear Style", "Anime Damage Markings Style",
    "Cute Anime Style"
]

    